laid_back_habitat/urls.py
# -*- coding: utf-8 -*-
"""laid_back_habitat URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^', include('orderRoom.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^(?P<link_value>[0-9]+)/$', views.test, name='test0'),
    url(r'^test/$', views.test, name='test'),
    url(r'^test/testGet/$', views.testGet, name='testGet'),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orderRoom/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    #login/logout
    url(r'^accounts/login/$', login),
    url(r'^accounts/logout/$', logout),

    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout),

    #query room
    url(r'^query_room/$', views.query_room, name='query_room'),
    #order room
    url(r'^BookingRoom/$', views.booking_room, name='booking_room'),
    #checkout
    url(r'^checkout/$', views.checkout, name='checkout'),
    #checkin
    url(r'^checkin/$', views.checkin, name='checkin'),
    #test View
    url(r'^order/(?P<pk>[0-9]+)/$', views.OrderView.as_view(), name='order'),
    #initial_models
    url(r'^initialModels/', views.initial_models, name='initial_models'),
    url(r'^createModelsData/', views.create_models_data, name='create_models_data'),
]

orderRoom/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Customer(models.Model):
    c_id = models.CharField(max_length=10, primary_key=True)
    c_name = models.CharField(max_length=255)
    c_phone = models.CharField(max_length=10)
    c_address = models.CharField(max_length=255, blank=True)

    def __str__(self):              # __unicode__ on Python 2
        return "%s, %s" % (self.c_id, self.c_name)

class Employee(models.Model):
    # e_id = models.IntegerField(default=0)
    e_name = models.CharField(max_length=255)
    e_phone = models.CharField(max_length=10)
    e_address = models.CharField(max_length=255, blank=False)

    def __str__(self):              # __unicode__ on Python 2
        return "%s" % (self.e_name)

class Cleaner(models.Model):
    # cl_id = models.IntegerField(default=0)
    cl_name = models.CharField(max_length=255)
    cl_phone = models.CharField(max_length=10)
    cl_address = models.CharField(max_length=255, blank=False)

    def __str__(self):              # __unicode__ on Python 2
        return "%s" % (self.cl_name)

class RoomType(models.Model):
    #rt_id = models. CharField(max_length=255, primary_key=True)
    rt_name = models.CharField(max_length=255)
    rt_money = models.IntegerField(default=0)

    def __str__(self):              # __unicode__ on Python 2
        return "%s, %s" % (self.rt_name, self.rt_money)

class Room (models.Model):
    # r_id = models.CharField(max_length=255)
    # r_type = models.CharField(max_length=255)

    r_name = models.CharField(max_length=255, primary_key=True)    
    # order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    room_type = models.ForeignKey(RoomType, on_delete=models.SET_NULL, null=True)
    # cleaner = models.ManyToManyField(Cleaner)

    def __str__(self):              # __unicode__ on Python 2
        return "%s, %s" % (self.r_name, self.room_type.rt_name)

class Order(models.Model):
    # p_id = models.IntegerField(default=0)
    o_date = models.DateTimeField()
    o_status = models.CharField(max_length=10)
    #Booking > Deposit > Checkout
    #c_id = models.CharField(max_length=10)
    #e_id = models.CharField(max_length=255)
    #r_id = models.CharField(max_length=255)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=False)
    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True)
    # Room = models.ForeignKey(Room)
    
    def __str__(self):              # __unicode__ on Python 2
        # return "Order: %s" % (self.o_date)
        return "%s, (%s)%s" % (self.o_date.date(), self.customer.c_id, self.customer.c_name)

class BookingRoom(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
    over_night_date = models.DateTimeField()

    def __str__(self):              # __unicode__ on Python 2
        return "%s, %s, %s" % (self.order, self.room, self.over_night_date.date())

class Payment(models.Model):
    # p_id = models.IntegerField(default=0)
    p_money = models.IntegerField(default=0)
    p_account = models.CharField(max_length=255)
    p_date = models.DateTimeField()

    order = models.OneToOneField(Order, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):              # __unicode__ on Python 2
        return "%s, %s, %s, %s" % (self.p_account, self.p_money, self.p_date, self.order)

class Service(models.Model):
    # s_id = models.IntegerField(default=0)
    s_bike = models.CharField(max_length=1)
    s_breakfast = models.CharField(max_length=1)
    s_gym = models.CharField(max_length=1)

    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)

    def __str__(self):              # __unicode__ on Python 2
        return "%s, %s, %s, %s" % (self.s_bike, self.s_breakfast, self.s_gym, self.order)

class CleanInfo(models.Model):
    # clinfo_id = models.IntegerField(default=0)
    # cl_id = models.IntegerField(default=0)
    # r_id = models.CharField(max_length=255)
    cl_date = models.DateTimeField()

    cleaner = models.ForeignKey(Cleaner, on_delete=models.SET_NULL, null=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)

    def __str__(self):              # __unicode__ on Python 2
        return "%s, (%s)%s, %s" % (self.cl_date, self.cleaner.id, self.cleaner.cl_name, self.room.r_name)

orderRoom/forms.py
from django import forms

class OrderForm(forms.Form):
	customer_id = forms.CharField(max_length=10)
	customer_name = forms.CharField(max_length=255)
	customer_phone = forms.CharField(max_length=10)
	customer_address = forms.CharField(max_length=255, required=False)

orderRoom/views.py
# -*- coding: utf-8 -*-
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response, get_list_or_404
from . import models
from .MyLib.MyDateTime import MyDateTime
from django.core.exceptions import ObjectDoesNotExist
from django.views import generic
from . import forms
import os
import datetime

class EmptyRoomTypeHistogram:
    def __total_room_num(self):
        target_room_type = models.RoomType.objects.filter(rt_name=self.room_type_name)
        return len(models.Room.objects.filter(room_type=target_room_type))

    def __curr_booking_room_list(self):
        target_room_type = models.RoomType.objects.get(rt_name=self.room_type_name)
        target_rooms = models.Room.objects.filter(room_type=target_room_type)
        from_datetime = self.from_date.date_time()
        to_datetime = self.to_date.date_time()
        return models.BookingRoom.objects.filter(room=target_rooms, over_night_date__range=(self.from_date.date_time(), self.to_date.date_time()))

    def __init__(self, room_type, str_from_date='', str_to_date=''):
        self.limit_days = 100
        if str_from_date and not str_to_date:
            self.room_type_id = room_type.id
            self.room_type_name = room_type.rt_name
            self.from_date = MyDateTime(str_from_date)
            self.to_date = MyDateTime(str_from_date)

            self.histogram = 0
            self.histogram = self.__total_room_num()

            for curr_booking in self.__curr_booking_room_list():
                self.histogram -= 1
                if self.histogram < 0:
                    self.histogram = 0

        elif str_from_date and str_to_date:
            self.room_type_id = room_type.id
            self.room_type_name = room_type.rt_name
            self.from_date = MyDateTime(str_from_date)
            self.to_date = MyDateTime(str_to_date)

            self.curr_range_days = abs(self.from_date.comprise_between(self.to_date))
            if self.curr_range_days > self.limit_days:
                return
            #initial
            range_days = self.from_date.comprise_everyday(self.to_date)

            self.histogram = {}
            for everyday in range_days:
                self.histogram[everyday.year] = {}

            for everyday in range_days:
                self.histogram[everyday.year][everyday.month] = {}

            for everyday in range_days:
                self.histogram[everyday.year][everyday.month][everyday.day] = self.__total_room_num()

            #set value
            for curr_booking in self.__curr_booking_room_list():
                year  = curr_booking.over_night_date.year
                month = curr_booking.over_night_date.month
                day   = curr_booking.over_night_date.day

                if year in self.histogram and month in self.histogram[year] and day in self.histogram[year][month]:
                    self.histogram[year][month][day] -= 1
                    if self.histogram[year][month][day] < 0:
                       self.histogram[year][month][day] = 0
class BookingUnit:
    #room:yyyy_mm_dd:yyyy_mm_dd
    def __init__(self, str_room_from_data_to_data):
        self.room_name, from_date, to_date = str_room_from_data_to_data.split(':')
        self.from_datetime = MyDateTime(from_date)
        self.to_datetime = MyDateTime(to_date)

    def total_day(self):
        return self.from_datetime.comprise_between(self.to_datetime)

    def every_night(self):
        return self.from_datetime.comprise_everyday(self.to_datetime)


# Create your views here.
def query_room(request):
    today_date = request.GET.get('today', '')
    from_date = request.GET.get('from', '')
    to_date = request.GET.get('to', '')

    if today_date:
        histogram=[]
        for room_type in list(models.RoomType.objects.all()):
            histogram_unit = EmptyRoomTypeHistogram(room_type, today_date)
            histogram.append(histogram_unit)

        return render_to_response('BookingList1.html', locals())
    elif from_date and to_date:
        histogram = []
        for room_type in list(models.RoomType.objects.all()):
            histogram_unit = EmptyRoomTypeHistogram(room_type, from_date, to_date)
            histogram.append(histogram_unit)
        # EmptyRoomTyppHistogram(models.RoomType.objects.all()[0], from_date, to_date)
        return render_to_response('BookingList2.html', locals())
    else:
        return render_to_response('BookingList1.html', locals())


def booking_room(request):
    get_data = request.GET
    default_datetime = ''
    default_room_type_id = ''
    if get_data:
        default_datetime = get_data.get('booking_datetime', '')
        default_room_type_id = get_data.get('booking_room_type_id', '')

    post_data = request.GET
    if 'customer_id' and \
       'customer_name' and \
       'customer_phone' and \
       'customer_address' in post_data and \
       'order_date' and\
       'booking[]' in post_data:

        target_customer=obj_cus = models.Customer()
        try:
            old_customer = models.Customer.objects.filter(\
                c_id=post_data['customer_id'])
            old_customer.update(
                c_phone = post_data['customer_phone'], \
                c_address = post_data['customer_address'])
            target_customer=old_customer[0]
        except (ObjectDoesNotExist, IndexError):
            new_customer = models.Customer.objects.create(\
                c_id=post_data['customer_id'],
                c_name=post_data['customer_name'],
                c_phone=post_data['customer_phone'],
                c_address=post_data['customer_address'])
            target_customer=new_customer


        new_order = models.Order.objects.create(
            o_date=post_data['order_date'],
            o_status='Booking',
            customer=target_customer)

        #booking['room_name:yyyy-mm-dd:yyyy-mm-dd']
        booking_list = post_data.getlist('booking[]')
        for str_room_from_to in booking_list:
            unit = BookingUnit(str_room_from_to)
            #sel_room = get_object_or_404(Room, r_name=unit.room_name)
            try:
                sel_room = models.Room.objects.filter(r_name=unit.room_name)[0]
            except (ObjectDoesNotExist, IndexError):
                raise Http404("room does not exist")

            every_night = unit.every_night()
            for night_datetime in every_night:
                models.BookingRoom.objects.create(\
                    over_night_date=night_datetime,\
                    order=new_order, \
                    room=sel_room)


    booking_room_form = forms.OrderForm()
    room_type_list = models.RoomType.objects.all();
    return render_to_response('BookingRoom.html',locals())
    #else:
    #    raise Http404("data does not exist")

def checkout(request):
    if 'cleaner_id' in request.GET:
        id = request.GET['cleaner_id']
        obj = models.Cleaner.objects.filter(id=id)[0]
        return HttpResponse(obj.cl_name + 'is a cleaner<br /> query be able to clean room');

    if 'employee_id' in request.POST:
        id = request.GET['employee_id']
        employee = models.Employee.objects.filter(id=id)[0]
        return HttpResponse(employee.e_name + 'is a employee<br />checkout for customer<br />change order status');

def checkin(request):
    if 'employee_id' in request.GET:
        id = request.GET['employee_id']
        employee = models.Employee.objects.filter(id=id)[0]
        return HttpResponse(employee.e_name + 'is a employee<br />query can checkin room');

    if 'employee_id' in request.POST:
        id = request.GET['employee_id']
        employee = models.Employee.objects.filter(id=id)[0]
        return HttpResponse(employee.e_name + 'is a employee<br />get pay from customer<br />change order status');
    elif 'cleaner_id' in request.POST:
        id = request.GET['cleaner_id']
        obj = models.Cleaner.objects.filter(id=id)[0]
        return HttpResponse(obj.cl_name + 'is a cleaner<br />clear room be used checkin');

def login(request):
    return HttpResponseRedirect('/accounts/login/')

def logout(request):
    return HttpResponseRedirect('/accounts/logout/')




'''
def order_room(request):
    from_str = request.POST.get('from', '')
    to_str = request.POST.get('to', '')
    if from_str and to_str:
        from_year, from_month, from_day = request.POST.get('from', '').split('-')
        from_datetime = datetime.datetime(int(from_year), int(from_month), int(from_day))

        to_year, to_month, to_day = request.POST.get('to', '').split('-')
        to_datetime = datetime.datetime(int(to_year), int(to_month), int(to_day))

        total_day = abs((to_datetime - from_datetime).days)
        return HttpResponse('客人您於' + str(from_datetime.date()) + '到' + str(to_datetime.date()) + '，有訂房。<br />祝你這' + str(total_day) + '天玩得開心。')
    else:
        return HttpResponse('您要兩個時都輸入，才能知道您訂房的狀況。')
        #return HttpResponseRedirect('/')
'''

class OrderView(generic.DetailView):
    model = models.Order
    #template_name = 'order_detail.html'
    #template_name = 'order_list.html'


def initial_models(request):
    os.system('initial_models.bat')
    return HttpResponse('')

def create_models_data(request):
    if not models.Customer.objects.filter(c_id='X173918116'):
        models.Customer.objects.create(c_id='X173918116', c_name='林伯彥', c_phone='0923415233', c_address='臺灣府城三界壇街')
    if not models.Customer.objects.filter(c_id='X163416802'):
        models.Customer.objects.create(c_id='X163416802', c_name='陳仙鶴', c_phone='0933958463', c_address='府城銀同里')
    if not models.Customer.objects.filter(c_id='X163416801'):
        models.Customer.objects.create(c_id='X163416801', c_name='陳復甫', c_phone='0933958463', c_address='明朝福建路漳州府龍溪')
    if not models.Customer.objects.filter(c_id='X160016836'):
        models.Customer.objects.create(c_id='X160016836', c_name='馮希範', c_phone='0939028276', c_address='泉州晉江縣')

orderRoom/templates/BookingList1.html
<!DOCTYPE html>
<html>
<head>
    <title>{{today_date}}</title>
    <meta charset='utf-8'>
</head>
<body>
    {% if today_date %}
    <h1>今天是 {{today_date}} </h1>
    <ul>
    {% for histogram_unit in histogram %}
        <li>{{ histogram_unit.room_type_name }} 的房型，還有 {{ histogram_unit.histogram }} 間房 </li>
    {% empty %}
        <li>尚未設定任何房型</li>
    {% endfor %}
    </ul>
    {% else %}
    <h1>日期不正確或不存在</h1>
    {% endif %}
</body>
</html>

orderRoom/templates/BookingList2.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <title>訂房!!</title>
    <style type="text/css">
        #ui-datepicker-div a{
            text-decoration: none;
            padding: 4px;
        }
        #ui-datepicker-div{
            font-family: monospace;
        }
        .ui-icon.ui-icon-circle-triangle-e{ color: #c0c0c0; }
        .ui-icon.ui-icon-circle-triangle-w{ color: #c0c0c0; }
    </style>
    <script type="text/javascript">
    function CallBookingRoomPage(button_id) {
    	var target_id = "form" + button_id
    	console.log(target_id)
		//document.getElementById(target_id).submit();
		//document.forms["form1"].elements[0].value = button_id
    }
    </script>
</head>
<body>
    {% include 'QueryEmptyRoomFrom.html' %}
    <h1>空房查詢明細</h1>
    {% for histogram_unit in histogram %}
    <table>
        <tr>
            <th>{{histogram_unit.room_type_name}}</th>
        </tr>
        {% for year, booking_dict in histogram_unit.histogram.items %}
        <tr>
            <td>{{year}} 年</td>
        </tr>
        {% for month, booking in booking_dict.items %}
        <tr>
            <td>{{month}} 月</td>
        </tr>
        <tr>
            <td>
                <table border="1">
                    <tr>
                        <td>
                            日
                        </td>
                        {% for day, booking_num in booking.items %}
                        <td width="16">
                            {{day}}
                        </td>
                        {% empty %}
                        <tr><td>日期設定有問題，請檢查日期是否正確</td></tr>
                        {% endfor %}
                    </tr>
                    <tr>
                        <td>
                            空房數
                        </td>
                        {% for day, booking_num in booking.items %}
                        <td>
                            {% if booking_num %}
                            <form id="form{{histogram_unit.room_type_id}}-{{year}}-{{month}}-{{day}}" method="get", action="{% url 'booking_room' %}">
                            <input type="submit" name="ok" value="{{booking_num}}"></input>
                            <input type="hidden" name="booking_datetime" value="{{year}}-{{month}}-{{day}}"></input>
                            <input type="hidden" name="booking_room_type_id" value="{{histogram_unit.room_type_id}}"></input>
                            </form>
                            {% else %}
                            {{booking_num}}
                            {% endif %}
                        </td>
                        {% empty %}
                        <tr><td>日期設定有問題，請檢查日期是否正確</td></tr>
                        {% endfor %}
                    </tr>
                </table>
            </td>
        </tr>
        {% empty %}
        <tr><td>日期設定有問題，請檢查日期是否正確, 或者查詢天數超過 {{histogram_unit.limit_days}} 天</td></tr>
        {% endfor %}
        {% empty %}
        <tr><td>日期設定有問題，請檢查日期是否正確, 或者查詢天數超過 {{histogram_unit.limit_days}} 天</td></tr>
        {% endfor %}
    </table>
    {% empty %}
    <h1>尚未設定任何房型</h1>
    {% endfor %}
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>

    <script src="{% static 'laid_back_habitat/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'laid_back_habitat/calTotalDays.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $("#datepicker1").datepicker({dateFormat:"yy-mm-dd",showMonthAfterYear:true});
        });
    </script>
    <script type="text/javascript">
        $(function() {
            $("#datepicker2").datepicker({dateFormat:"yy-mm-dd",showMonthAfterYear:true});
        });
    </script>
</body>
</html>

orderRoom/templates/BookingRoom.html
<!DOCTYPE html>
<html>
	<head>
		<title>訂房!!</title>
		<style type="text/css">
			#ui-datepicker-div a {
				text-decoration: none;
				padding: 4px;
			}
			#ui-datepicker-div {
				font-family: monospace;
			}
			.ui-icon.ui-icon-circle-triangle-e {
				color: #c0c0c0;
			}
			.ui-icon.ui-icon-circle-triangle-w {
				color: #c0c0c0;
			}

		</style>
		<script type="text/javascript">
			function AddBooking() {
				var from_date = document.getElementById('from_date').value;
				var to_date = document.getElementById('to_date').value;
				var room_type_id = document.getElementById('RoomType').value;

				var room_type_name = document.getElementById('RoomType').selectedOptions[0].innerHTML;

				if (from_date === '' | to_date === '' | room_type_id === '') {
					return 0;
				}

				var new_booking_room = document.createElement('li');
				var text = room_type_name + ":" + from_date + ":" + to_date;
				var textnode = document.createTextNode(text);
				new_booking_room.appendChild(textnode);
				var atti_name = document.createAttribute("name");
				atti_name.value = 'booking[]';
				new_booking_room.setAttributeNode(atti_name);

				document.getElementById("BookingRoomList").appendChild(new_booking_room);
			}
		</script>

	</head>
	<body>
		<form action="" method="post">
			<ul>
				<li>
					<label for="id_customer_id">身份證/護照 號碼:</label>
					<input id="id_customer_id" maxlength="10" name="customer_id" type="text"/>
				</li>
				<li>
					<label for="id_customer_name">名字:</label>
					{% if request.user.is_authenticated %}
						<input id="id_customer_name" maxlength="255" name="customer_name" type="text" value="{{request.user}}"/>
					{% else %}
						<input id="id_customer_name" maxlength="255" name="customer_name" type="text"/>
					{% endif %}
				</li>
				<li>
					<label for="id_customer_phone">聯絡電話:</label>
					<input id="id_customer_phone" maxlength="10" name="customer_phone" type="text"/></li>
				<li>
					<label for="id_customer_address">聯絡地址:</label>
					<input id="id_customer_address" maxlength="255" name="customer_address" type="text"/></li>
				<li>
					<label>選擇房型&日期:</label>
					{% if room_type_list %}
						<select id="RoomType" name='room_type'>
							{% for room_type in room_type_list %}
								{% if forloop.first %}
									{% if default_room_type_id %}
										{% if default_room_type_id == room_type.id %}
											<option value="{{room_type.id}}" selected>{{room_type.rt_name}}</option>
										{% else %}
											<option value="{{room_type.id}}">{{room_type.rt_name}}</option>
										{% endif %}
									{% else %}
										<option value="{{room_type.id}}" selected>{{room_type.rt_name}}</option>
									{% endif %}
								{% else %}
									{% if default_room_type_id %}
										{% if default_room_type_id == room_type.id %}
											<option value="{{room_type.id}}" selected>{{room_type.rt_name}}</option>
										{% else %}
											<option value="{{room_type.id}}">{{room_type.rt_name}}</option>

										{% endif %}
									{% else %}
										<option value="{{room_type.id}}">{{room_type.rt_name}}</option>
									{% endif %}
								{% endif %}
							{% endfor %}
						</select>
					{% endif %}

					{% if default_datetime %}
						<input type="text" id="from_date" name="from" value="{{default_datetime}}">
						<input type="text" id="to_date" name="to" value="{{default_datetime}}">
					{% else %}
						<input type="text" id="from_date" name="from" placeholder="從幾月幾號">
						<input type="text" id="to_date" name="to" placeholder="到幾月幾號">
					{% endif %}
					<input type="button" value="加" onclick="AddBooking()"/>
					<ul id="BookingRoomList"/>
				</li>
			</ul>
		</form>
		{% load staticfiles %}
		<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
		<script src="{% static 'laid_back_habitat/jquery-ui/jquery-ui.min.js' %}"></script>
		<script type="text/javascript">
			$(function () {
				$("#from_date").datepicker({dateFormat: "yy-mm-dd", showMonthAfterYear: true});
			});
		</script>
		<script type="text/javascript">
			$(function () {
				$("#to_date").datepicker({dateFormat: "yy-mm-dd", showMonthAfterYear: true});
			});
		</script>
	</body>
</html>

orderRoom/templates/QueryEmptyRoomFrom.html
{% if request.user.is_authenticated %}
    <div id="hello_user">{{request.user}}, 歡迎來玩</div>
{% endif %}
<form action="/query_room/" method="get">
    <input type="text" id="datepicker1" name="from" placeholder="從幾月幾號" value={{from_date}}>
    <input type="text" id="datepicker2" name="to" placeholder="到幾月幾號" value={{to_date}}>
    <input type="submit" value="查詢空房">
</form>

orderRoom/templates/index.html
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
    <title>訂房!!</title>
    <style type="text/css">
        #ui-datepicker-div a{
            text-decoration: none;
            padding: 4px;
        }
        #ui-datepicker-div{
            font-family: monospace;
        }
        .ui-icon.ui-icon-circle-triangle-e{ color: #c0c0c0; }
        .ui-icon.ui-icon-circle-triangle-w{ color: #c0c0c0; }
    </style>
</head>
<body>
	{% include 'QueryEmptyRoomFrom.html' %}
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>

    <script src="{% static 'laid_back_habitat/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'laid_back_habitat/calTotalDays.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $("#datepicker1").datepicker({dateFormat:"yy-mm-dd",showMonthAfterYear:true});
        });
    </script>
    <script type="text/javascript">
        $(function() {
            $("#datepicker2").datepicker({dateFormat:"yy-mm-dd",showMonthAfterYear:true});
        });
    </script>
</body>
</html>

orderRoom/templates/test.html
<!DOCTYPE html>
<html>
<head>
    <title>測試!!</title>
</head>
<body>
    <form method="get" action="testGet" >
       <input type="text" name="good[0][room]" value="room1"/><br />
       <input type="text" name="good[0][from]" value="2016-06-01"/><br />
       <input type="text" name="good[0][to]" value="2016-06-07"/><br />
       <input type="text" name="good[1][room]" value="room2"/><br />
       <input type="text" name="good[2][from]" value="2016-07-01"/><br />
       <input type="text" name="good[2][to]" value="2016-07-08"/><br />
       <input type="submit" value="submit"/>
    </form>
</body>
</html>